# Generated by Django 5.2.14 on 2026-05-31 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('organization_type', models.CharField(choices=[('company', 'Company'), ('ngo', 'NGO'), ('government', 'Government Office'), ('school', 'School or Institution'), ('health', 'Health Facility'), ('other', 'Other')], default='company', max_length=30)),
                ('sector', models.CharField(blank=True, max_length=120)),
                ('address', models.TextField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=140)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('website', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InternshipPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(max_length=160)),
                ('department', models.CharField(blank=True, max_length=140)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('workplace_supervisor_name', models.CharField(blank=True, max_length=140)),
                ('workplace_supervisor_email', models.EmailField(blank=True, max_length=254)),
                ('workplace_supervisor_phone', models.CharField(blank=True, max_length=40)),
                ('learning_objectives', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='core.hostorganization')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervised_placements', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internship_placements', to='core.program')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_placements', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internship_placements', to='core.academicterm')),
            ],
            options={
                'ordering': ['-start_date', 'student__username'],
                'unique_together': {('student', 'host_organization', 'term')},
            },
        ),
        migrations.CreateModel(
            name='InternshipEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluator_role', models.CharField(choices=[('instructor', 'Instructor'), ('host_supervisor', 'Host Supervisor')], default='instructor', max_length=30)),
                ('technical_score', models.PositiveSmallIntegerField(default=0)),
                ('professionalism_score', models.PositiveSmallIntegerField(default=0)),
                ('communication_score', models.PositiveSmallIntegerField(default=0)),
                ('attendance_score', models.PositiveSmallIntegerField(default=0)),
                ('comments', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='core.internshipplacement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('remote', 'Remote')], default='present', max_length=20)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.internshipplacement')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('placement', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LogbookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('hours_worked', models.DecimalField(decimal_places=1, default=8, max_digits=4)),
                ('activities', models.TextField()),
                ('skills_learned', models.TextField(blank=True)),
                ('challenges', models.TextField(blank=True)),
                ('next_plan', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='draft', max_length=20)),
                ('instructor_feedback', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logbook_entries', to='core.internshipplacement')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_logbook_entries', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logbook_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entry_date', '-created_at'],
                'unique_together': {('placement', 'entry_date')},
            },
        ),
    ]
